version: '3.9'

services:
  factorial_api:
    build: ./factorial_api
    container_name: factorial_api
    ports:
      - "8000:8000"

  fibonacci_api:
    build: ./fibonacci_api
    container_name: fibonacci_api
    ports:
      - "8001:8001"
    depends_on:
      - factorial_api

  user_interface:
    build: ./user_interface
    container_name: user_interface
    ports:
      - "8002:8002"
    depends_on:
      - fibonacci_api